### ISSUE TITLE
Unable to complete 'make' command - compiler issue, maybe? 

### ISSUE THREAD

**Issue by jojobee75** [wedesoft/anymeal#17]
Hello. I'm trying to install your application on Ubuntu 18.04 and I'm getting an error while trying to execute the MAKE command. It's quite possible I'm doing something wrong, since I'm a complete n00b. Here is the error I'm getting....
make  all-recursive
make[1]: Entering directory '/home/joe/Downloads/anymeal-1.4'
Making all in anymeal
make[2]: Entering directory '/home/joe/Downloads/anymeal-1.4/anymeal'
make  all-recursive
make[3]: Entering directory '/home/joe/Downloads/anymeal-1.4/anymeal'
Making all in locale
make[4]: Entering directory '/home/joe/Downloads/anymeal-1.4/anymeal/locale'
Making all in de
make[5]: Entering directory '/home/joe/Downloads/anymeal-1.4/anymeal/locale/de'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/joe/Downloads/anymeal-1.4/anymeal/locale/de'
make[5]: Entering directory '/home/joe/Downloads/anymeal-1.4/anymeal/locale'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/home/joe/Downloads/anymeal-1.4/anymeal/locale'
make[4]: Leaving directory '/home/joe/Downloads/anymeal-1.4/anymeal/locale'
make[4]: Entering directory '/home/joe/Downloads/anymeal-1.4/anymeal'
g++ -DHAVE_CONFIG_H -I. -I..    -DLOCALEDIR=\"/usr/share/locale\" -I/usr/include -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_DBUS_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_TESTLIB_LIB -DQT_XML_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR="/tmp" -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtTest -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++  -g -O2 -MT anymeal-moc_main_window.o -MD -MP -MF .deps/anymeal-moc_main_window.Tpo -c -o anymeal-moc_main_window.o `test -f 'moc_main_window.cc' || echo './'`moc_main_window.cc
moc_main_window.cc:149:1: **error: ‘QT_INIT_METAOBJECT’** does not name a type; did you mean ‘**Q_INIT_RESOURCE’?**
 QT_INIT_METAOBJECT const QMetaObject MainWindow::staticMetaObject = {
 ^~~~~~~~~~~~~~~~~~
 Q_INIT_RESOURCE
Makefile:875: recipe for target 'anymeal-moc_main_window.o' failed
make[4]: *** [anymeal-moc_main_window.o] Error 1
make[4]: Leaving directory '/home/joe/Downloads/anymeal-1.4/anymeal'
Makefile:1183: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/joe/Downloads/anymeal-1.4/anymeal'
Makefile:535: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/joe/Downloads/anymeal-1.4/anymeal'
Makefile:423: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/joe/Downloads/anymeal-1.4'
Makefile:355: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wedesoft** [comment]
You need to delete the MOC files: "rm anymeal/moc_*.cc". Then try "make" again. Let me know if it does not work.

Am 26. Juli 2020 13:28:44 GMT+01:00 schrieb jojobee75 <notifications@github.com>:
>Hello. I'm trying to install your application on Ubuntu 18.04 and I'm
>getting an error while trying to execute the MAKE command. It's quite
>possible I'm doing something wrong, since I'm a complete n00b. Here is
>the error I'm getting....>
>make  all-recursive>
>make[1]: Entering directory '/home/joe/Downloads/anymeal-1.4'>
>Making all in anymeal>
>make[2]: Entering directory '/home/joe/Downloads/anymeal-1.4/anymeal'>
>make  all-recursive>
>make[3]: Entering directory '/home/joe/Downloads/anymeal-1.4/anymeal'>
>Making all in locale>
>make[4]: Entering directory
>'/home/joe/Downloads/anymeal-1.4/anymeal/locale'>
>Making all in de>
>make[5]: Entering directory
>'/home/joe/Downloads/anymeal-1.4/anymeal/locale/de'>
>make[5]: Nothing to be done for 'all'.>
>make[5]: Leaving directory
>'/home/joe/Downloads/anymeal-1.4/anymeal/locale/de'>
>make[5]: Entering directory
>'/home/joe/Downloads/anymeal-1.4/anymeal/locale'>
>make[5]: Nothing to be done for 'all-am'.>
>make[5]: Leaving directory
>'/home/joe/Downloads/anymeal-1.4/anymeal/locale'>
>make[4]: Leaving directory
>'/home/joe/Downloads/anymeal-1.4/anymeal/locale'>
>make[4]: Entering directory '/home/joe/Downloads/anymeal-1.4/anymeal'>
>g++ -DHAVE_CONFIG_H -I. -I..    -DLOCALEDIR=\"/usr/share/locale\"
>-I/usr/include -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG
>-DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB
>-DQT_DBUS_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_TESTLIB_LIB
>-DQT_XML_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR="/tmp" -I. -isystem
>/usr/include/x86_64-linux-gnu/qt5 -isystem
>/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem
>/usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem
>/usr/include/x86_64-linux-gnu/qt5/QtGui -isystem
>/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem
>/usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem
>/usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem
>/usr/include/x86_64-linux-gnu/qt5/QtSql -isystem
>/usr/include/x86_64-linux-gnu/qt5/QtTest -isystem
>/usr/include/x86_64-linux-gnu/qt5/QtXml -isystem
>/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem
>/usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ 
>-g -O2 -MT anymeal-moc_main_window.o -MD -MP -MF
>.deps/anymeal-moc_main_window.Tpo -c -o anymeal-moc_main_window.o `test
>-f 'moc_main_window.cc' || echo './'`moc_main_window.cc>
>moc_main_window.cc:149:1: **error: ‘QT_INIT_METAOBJECT’** does not name
>a type; did you mean ‘**Q_INIT_RESOURCE’?**>
> QT_INIT_METAOBJECT const QMetaObject MainWindow::staticMetaObject = {>
> ^~~~~~~~~~~~~~~~~~>
> Q_INIT_RESOURCE>
>Makefile:875: recipe for target 'anymeal-moc_main_window.o' failed>
>make[4]: *** [anymeal-moc_main_window.o] Error 1>
>make[4]: Leaving directory '/home/joe/Downloads/anymeal-1.4/anymeal'>
>Makefile:1183: recipe for target 'all-recursive' failed>
>make[3]: *** [all-recursive] Error 1>
>make[3]: Leaving directory '/home/joe/Downloads/anymeal-1.4/anymeal'>
>Makefile:535: recipe for target 'all' failed>
>make[2]: *** [all] Error 2>
>make[2]: Leaving directory '/home/joe/Downloads/anymeal-1.4/anymeal'>
>Makefile:423: recipe for target 'all-recursive' failed>
>make[1]: *** [all-recursive] Error 1>
>make[1]: Leaving directory '/home/joe/Downloads/anymeal-1.4'>
>Makefile:355: recipe for target 'all' failed>
>make: *** [all] Error 2>
>>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/wedesoft/anymeal/issues/17

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jojobee75** [comment]
That worked! Thank you for the extremely quick response!

**Comment by wedesoft** [comment]
Ok, glad that it solved the problem.
