### ISSUE TITLE
Meal master import

### ISSUE THREAD

**Issue by RodMyers** [wedesoft/anymeal#18]
anymeal 1.5
Debian GNU/Linux 10 (buster) x86_64

gourmet export 1 recipe as a test in mealmaster format. Attemptng to move recipes to anymeal

attached is the test file that fails with this error, taken from /tmp/errors.mmf
================================
Rejected recipe: Problem in state 6 and line 5: unexpected character 'P'
MMMMM----- Recipe via Meal-Master (tm)

   Title: 04 - kimchi
Categories: Asian/Korean, Health
Preparation Time: 25 minutes
    Link: http://www.chowhound.com/recipes/basic-napa-cabbage-kimchi-kimchee-29505

     1    (2-pound) napa cabbage
   1/2  c kosher salt
    12  c cold water, plus more as needed
     8 oz daikon radish, peeled and cut into 2-inch matchsticks
     4 md scallions, ends trimmed, cut into 1-inch pieces (use all parts)
   1/4  c fish sauce
   1/4  c peeled and minced fresh ginger (from about a 2-ounce piece)
     1 tb minced garlic cloves (from 6 to 8 medium cloves)
     2  t Korean salted shrimp, minced
 1 1/2  t granulated sugar

  1:      Cut the cabbage in half lengthwise, then crosswise into 2-inch
  pieces, discarding the root end. Place in a large bowl, sprinkle with
  the salt, and toss with your hands until the cabbage is coated. Add
  enough cold water to just cover (about 12 cups), making sure the
  cabbage is submerged (it’s OK if a few leaves break the surface).
  /assets/2014/10/29505_kimchee_inline_640_1.jpg! Cover with plastic
  wrap or a baking sheet and let sit at room temperature at least 12
  hours and up to 24 hours.
  
  
  2:      Place a colander in the sink, drain the cabbage, and rinse
  with cold water. Gently squeeze out the excess liquid and transfer to
  a medium bowl; set aside.
  
  
  3:      Place the remaining ingredients in a large bowl and stir to
  combine. Add the cabbage and toss with your hands until evenly
  combined and the cabbage is thoroughly coated with the mixture. Pack
  the mixture tightly into a clean 2-quart or 2-liter glass jar with a
  tightfitting lid and seal the jar. Let sit in a cool, dark place for
  24 hours (the mixture may bubble). Open the jar to let the gases
  escape, then reseal and refrigerate at least 48 hours before eating
  (kimchi is best after fermenting about 1 week). Refrigerate for up to
  1 month.
  
  
  Rating: 4.5/5 stars
  
  Summary
  
  
  Kimchi is a traditional Korean dish of fermented vegetables, the most
  common of which are napa cabbage and daikon radish. In addition to
  being served as banchan, Korean side dishes presented as part of a
  meal, it can also be used in a variety of cooked dishes. Try it as a
  sauce for Brussels sprouts or braised with short ribs. The versatility
  of kimchi makes it great to use in everyday cooking.
  
  
  Game plan: Kimchi needs time to ferment, so we recommend starting a
  batch about a week before you plan to use it.
  
  
  What to buy: Korean red pepper powder or kochukaru is what gives
  kimchee its spiciness. It can be found in Korean markets in large
  resealable plastic bags, in different grades of coarseness and
  spiciness. Choose a grade based on your personal preference.
  
  
  Also known as saeujeot, Korean salted shrimp are very small, naturally
  fermented shrimp that impart authentic flavor to kimchi. They are sold
  in jars and can be found in the refrigerator case of Korean markets.
  
  
  Special equipment: You will need a clean 2-quart or 2-liter glass jar
  with a tightfitting lid to hold the kimchi while it ferments. Do not
  use plastic, as the odors from the kimchi can be hard to remove from
  plastic.
  
  
  More kimchi recipes.
  
  by Christine Gallary
  

MMMMM

[kimchi.mmf.txt](https://github.com/wedesoft/anymeal/files/4996081/kimchi.mmf.txt)

**Comment by wedesoft** [comment]
Hi,
The recipe was not correctly formatted. The MealMaster format does not have a preparation time entry. However it needs a servings/yield entry. Also the ingredients need to be indented correctly. The following modified recipe should work:

```
MMMMM----- Recipe via Meal-Master (tm)

     Title: Kimchi
Categories: Asian/Korean, Health
     Yield: 6 servings

      1    (2-pound) napa cabbage
    1/2 c  kosher salt
     12 c  cold water, plus more as needed
      8 oz daikon radish, peeled and cut into 2-inch matchsticks
      4 md scallions, ends trimmed, cut into 1-inch pieces (use all parts)
    1/4 c  fish sauce
    1/4 c  peeled and minced fresh ginger (from about a 2-ounce piece)
      1 tb minced garlic cloves (from 6 to 8 medium cloves)
      2 t  Korean salted shrimp, minced
  1 1/2 t  granulated sugar

1: Cut the cabbage in half lengthwise, then crosswise into 2-inch
pieces, discarding the root end. Place in a large bowl, sprinkle with
the salt, and toss with your hands until the cabbage is coated. Add
enough cold water to just cover (about 12 cups), making sure the
cabbage is submerged (it’s OK if a few leaves break the surface).
/assets/2014/10/29505_kimchee_inline_640_1.jpg! Cover with plastic
wrap or a baking sheet and let sit at room temperature at least 12
hours and up to 24 hours.

2: Place a colander in the sink, drain the cabbage, and rinse
with cold water. Gently squeeze out the excess liquid and transfer to
a medium bowl; set aside.

3: Place the remaining ingredients in a large bowl and stir to
combine. Add the cabbage and toss with your hands until evenly
combined and the cabbage is thoroughly coated with the mixture. Pack
the mixture tightly into a clean 2-quart or 2-liter glass jar with a
tightfitting lid and seal the jar. Let sit in a cool, dark place for
24 hours (the mixture may bubble). Open the jar to let the gases
escape, then reseal and refrigerate at least 48 hours before eating
(kimchi is best after fermenting about 1 week). Refrigerate for up to
1 month.

Rating: 4.5/5 stars

Link: http://www.chowhound.com/recipes/basic-napa-cabbage-kimchi-kimchee-29505

Preparation Time: 25 minutes

Summary

Kimchi is a traditional Korean dish of fermented vegetables, the most
common of which are napa cabbage and daikon radish. In addition to
being served as banchan, Korean side dishes presented as part of a
meal, it can also be used in a variety of cooked dishes. Try it as a
sauce for Brussels sprouts or braised with short ribs. The versatility
of kimchi makes it great to use in everyday cooking.

Game plan: Kimchi needs time to ferment, so we recommend starting a
batch about a week before you plan to use it.

What to buy: Korean red pepper powder or kochukaru is what gives
kimchee its spiciness. It can be found in Korean markets in large
resealable plastic bags, in different grades of coarseness and
spiciness. Choose a grade based on your personal preference.

Also known as saeujeot, Korean salted shrimp are very small, naturally
fermented shrimp that impart authentic flavor to kimchi. They are sold
in jars and can be found in the refrigerator case of Korean markets.

Special equipment: You will need a clean 2-quart or 2-liter glass jar
with a tightfitting lid to hold the kimchi while it ferments. Do not
use plastic, as the odors from the kimchi can be hard to remove from
plastic.

More kimchi recipes.

by Christine Gallary

MMMMM
```

**Comment by RodMyers** [comment]
And this is why I am trying to get away from the program gourmet.

I will try your edit, and then do the gourmet export, 1 at a time.

Thank you

**Comment by wedesoft** [comment]
Ok, no problem. Thanks for trying out the software. Hope it will work for you.

**Comment by RodMyers** [comment]
just walked in the door. tested your edit. it works.

now to export every recipe one at a time to get them to import correctly

**Comment by wedesoft** [comment]
You can import multiple recipes. You can then copy the /tmp/errors.mmf file to $HOME, edit it, and then reimport it. You can then repeat this process until you end up with an empty /tmp/errors.mmf file.

**Comment by RodMyers** [comment]
1 issue left. All of the rest of recipes are erroring out with the same/smiliar issue

they all have 2 lines. Title and Category, followed by a blank line. Not sure what is happening
= = = = = = 

Rejected recipe: Problem in state 6 and line 5: unexpected newline
MMMMM----- Recipe via Meal-Master (tm)

   Title: 02 - theresa sausage balls
Categories: Snack, Snack

     1 lb sausage
     2  c shredded cheddar cheese
     2  c bisquick


  Mix together, then roll in to balls. Cook at 325 degrees for 15 min or
  until golden brown.
  
  **Note** I always doubled the recipe, using 1 lb mild & 1 lb hot
  sausage, but cut the sausage in half using half of each in each batch,
  because it is easier to mix one batch at a time.  if this doesn't make
  sense, ask me.
  
  
  IF GOING TO FREEZE: freeze before cooking them
  

MMMMM
Rejected recipe: Problem in state 6 and line 5: unexpected newline
MMMMM----- Recipe via Meal-Master (tm)

   Title: 04 - kimchi
Categories: Asian/Korean, Health

     1   2lb napa cabbage
   1/2  c kosher salt
    12  c cold water, plus more as needed
     8 oz daikon radish, peeled and cut into 2-inch matchsticks
     4 md scallions, ends trimmed, cut into 1-inch pieces (use all parts)
   1/4  c fish sauce
   1/4  c peeled and minced fresh ginger (from about a 2-ounce piece)
     1 tb minced garlic cloves (from 6 to 8 medium cloves)
     2  t Korean salted shrimp, minced
 1 1/2  t granulated sugar


  1:      Cut the cabbage in half lengthwise, then crosswise into 2-inch
  pieces, discarding the root end. Place in a large bowl, sprinkle with
  the salt, and toss with your hands until the cabbage is coated. Add
  enough cold water to just cover (about 12 cups), making sure the
  cabbage is submerged (it’s OK if a few leaves break the surface).
  /assets/2014/10/29505_kimchee_inline_640_1.jpg! Cover with plastic
  wrap or a baking sheet and let sit at room temperature at least 12
  hours and up to 24 hours.
  
  
  2:      Place a colander in the sink, drain the cabbage, and rinse
  with cold water. Gently squeeze out the excess liquid and transfer to
  a medium bowl; set aside.
  
  
  3:      Place the remaining ingredients in a large bowl and stir to
  combine. Add the cabbage and toss with your hands until evenly
  combined and the cabbage is thoroughly coated with the mixture. Pack
  the mixture tightly into a clean 2-quart or 2-liter glass jar with a
  tightfitting lid and seal the jar. Let sit in a cool, dark place for
  24 hours (the mixture may bubble). Open the jar to let the gases
  escape, then reseal and refrigerate at least 48 hours before eating
  (kimchi is best after fermenting about 1 week). Refrigerate for up to
  1 month.
  
  
  Rating: 4.5/5 stars
  
  Summary
  
  
  Kimchi is a traditional Korean dish of fermented vegetables, the most
  common of which are napa cabbage and daikon radish. In addition to
  being served as banchan, Korean side dishes presented as part of a
  meal, it can also be used in a variety of cooked dishes. Try it as a
  sauce for Brussels sprouts or braised with short ribs. The versatility
  of kimchi makes it great to use in everyday cooking.
  
  
  Game plan: Kimchi needs time to ferment, so we recommend starting a
  batch about a week before you plan to use it.
  
  
  What to buy: Korean red pepper powder or kochukaru is what gives
  kimchee its spiciness. It can be found in Korean markets in large
  resealable plastic bags, in different grades of coarseness and
  spiciness. Choose a grade based on your personal preference.
  
  
  Also known as saeujeot, Korean salted shrimp are very small, naturally
  fermented shrimp that impart authentic flavor to kimchi. They are sold
  in jars and can be found in the refrigerator case of Korean markets.
  
  
  Special equipment: You will need a clean 2-quart or 2-liter glass jar
  with a tightfitting lid to hold the kimchi while it ferments. Do not
  use plastic, as the odors from the kimchi can be hard to remove from
  plastic.
  
  
  More kimchi recipes.
  
  by Christine Gallary
  

MMMMM

**Comment by wedesoft** [comment]
The recipes were missing the `Servings` or `Yield` line. Also the ingredients need to be indented correctly:

```
MMMMM----- Recipe via Meal-Master (tm)

     Title: 02 - theresa sausage balls
Categories: Snack
  Servings: 4 servings

      2 tb vinegar
      1 lb sausage
      2 c  shredded cheddar cheese
      2 c  bisquick

Mix together, then roll in to balls. Cook at 325 degrees for 15 min or
until golden brown.

Note I always doubled the recipe, using 1 lb mild & 1 lb hot
sausage, but cut the sausage in half using half of each in each batch,
because it is easier to mix one batch at a time. if this doesn't make
sense, ask me.

IF GOING TO FREEZE: freeze before cooking them

MMMMM

MMMMM----- Recipe via Meal-Master (tm)

     Title: 04 - kimchi
Categories: Asian/Korean, Health
  Servings: 4 servings

      1    2lb napa cabbage
    1/2 c  kosher salt
     12 c  cold water, plus more as needed
      8 oz daikon radish, peeled and cut into 2-inch matchsticks
      4 md scallions, ends trimmed, cut into 1-inch pieces (use all parts)
    1/4 c  fish sauce
    1/4 c  peeled and minced fresh ginger (from about a 2-ounce piece)
      1 tb minced garlic cloves (from 6 to 8 medium cloves)
      2 t  Korean salted shrimp, minced
  1 1/2 t  granulated sugar

1: Cut the cabbage in half lengthwise, then crosswise into 2-inch
pieces, discarding the root end. Place in a large bowl, sprinkle with
the salt, and toss with your hands until the cabbage is coated. Add
enough cold water to just cover (about 12 cups), making sure the
cabbage is submerged (it’s OK if a few leaves break the surface).
/assets/2014/10/29505_kimchee_inline_640_1.jpg! Cover with plastic
wrap or a baking sheet and let sit at room temperature at least 12
hours and up to 24 hours.

2: Place a colander in the sink, drain the cabbage, and rinse
with cold water. Gently squeeze out the excess liquid and transfer to
a medium bowl; set aside.

3: Place the remaining ingredients in a large bowl and stir to
combine. Add the cabbage and toss with your hands until evenly
combined and the cabbage is thoroughly coated with the mixture. Pack
the mixture tightly into a clean 2-quart or 2-liter glass jar with a
tightfitting lid and seal the jar. Let sit in a cool, dark place for
24 hours (the mixture may bubble). Open the jar to let the gases
escape, then reseal and refrigerate at least 48 hours before eating
(kimchi is best after fermenting about 1 week). Refrigerate for up to
1 month.

Rating: 4.5/5 stars

Summary

Kimchi is a traditional Korean dish of fermented vegetables, the most
common of which are napa cabbage and daikon radish. In addition to
being served as banchan, Korean side dishes presented as part of a
meal, it can also be used in a variety of cooked dishes. Try it as a
sauce for Brussels sprouts or braised with short ribs. The versatility
of kimchi makes it great to use in everyday cooking.

Game plan: Kimchi needs time to ferment, so we recommend starting a
batch about a week before you plan to use it.

What to buy: Korean red pepper powder or kochukaru is what gives
kimchee its spiciness. It can be found in Korean markets in large
resealable plastic bags, in different grades of coarseness and
spiciness. Choose a grade based on your personal preference.

Also known as saeujeot, Korean salted shrimp are very small, naturally
fermented shrimp that impart authentic flavor to kimchi. They are sold
in jars and can be found in the refrigerator case of Korean markets.

Special equipment: You will need a clean 2-quart or 2-liter glass jar
with a tightfitting lid to hold the kimchi while it ferments. Do not
use plastic, as the odors from the kimchi can be hard to remove from
plastic.

More kimchi recipes.

by Christine Gallary

MMMMM
```

**Comment by RodMyers** [comment]
attached are the last 6 or 7.

I do not see any obvious errors

thank you

[ready.mmf.txt](https://github.com/wedesoft/anymeal/files/5028436/ready.mmf.txt)

**Comment by wedesoft** [comment]
There are mostly indentation issues. The modified file should import without a problem: [readyx.mmf.txt](https://github.com/wedesoft/anymeal/files/5031080/readyx.mmf.txt)

**Comment by RodMyers** [comment]
i would never have known that.

thank you
