### ISSUE TITLE
Does not run on Ubuntu xenial

### ISSUE THREAD

**Issue by probonopd** [wedesoft/anymeal#19]
Please build on Ubuntu xenial or earlier, so that the AppImage can run on all still-supported versions of Ubuntu. Thank you very much!

```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /run/firejail/appimage/.appimage-9355/usr/bin/../lib/libsqlite3.so.0
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/2299

**Comment by wedesoft** [comment]
Hi, I tried building on Ubuntu Xenial but the linuxdeploy-qt-plugin crashes.
I also tried Debian 9 but there the linuxdeploy AppImage is too recent.

Am 24. August 2020 22:39:41 GMT+01:00 schrieb probonopd <notifications@github.com>:
>Please build on Ubuntu xenial or earlier, so that the AppImage can run
>on all still-supported versions of Ubuntu. Thank you very much!
>
>```
>/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found
>(required by
>/run/firejail/appimage/.appimage-9355/usr/bin/../lib/libsqlite3.so.0
>```
>
>Reference:
>https://github.com/AppImage/appimage.github.io/pull/2299
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wedesoft/anymeal/issues/19

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by probonopd** [comment]
> Hi, I tried building on Ubuntu Xenial but the linuxdeploy-qt-plugin crashes.

Thanks for trying. Could you please open an issue with some information on how to reproduce the crash over at https://github.com/linuxdeploy/linuxdeploy-plugin-qt/issues?

**Comment by wedesoft** [comment]
Sorry, I realized that I actually I tried it on a Bionic Beaver machine (I have opened [issue 73](https://github.com/linuxdeploy/linuxdeploy-plugin-qt/issues/73) in the linuxdeploy-plugin-qt). Will now try building on Xenial using Docker.

**Comment by wedesoft** [comment]
The Qt version of Ubuntu Xenial does not support "QOverload". Also the C++ compiler does not support more recent features such as "auto".

**Comment by probonopd** [comment]
Please use a recent Qt version for xenial then, e.g., from https://launchpad.net/~beineri.

**Comment by wedesoft** [comment]
Well, I can have another look into it. Maybe I need to use the old SIGNAL, SLOT syntax instead of QOverload.

**Comment by wedesoft** [comment]
Ok, I have backported the code to compile with the older compiler and built [anymeal-0d52131-x86_64.AppImage](https://github.com/wedesoft/anymeal/releases/download/v1.7/anymeal-0d52131-x86_64.AppImage) under Ubuntu Xenial. Let me know if it works.

**Comment by wedesoft** [comment]
For some reason the image does not work on Xenial. I deleted the AppDir and rebuilt it again. But now I get the following error when trying to run the AppImage:

```
This application failed to start because it could not find or load the Qt platform plugin "xcb".
```

**Comment by probonopd** [comment]
Thans for trying @wedesoft. If you can upload the non-working one somewhere, I can have a look at it.

**Comment by wedesoft** [comment]
Thanks for looking into it. I would be happy if AnyMeal would work on older distributions. I have uploaded [anymeal-e7df77c-x86_64.AppImage](http://www.wedesoft.de/downloads/anymeal-e7df77c-x86_64.AppImage). I didn't manage to get X11 running in the container so I haven't tested it under Xenial. But running it on Debian 10 gives the following error:
```
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Reinstalling the application may fix this problem.
Abgebrochen
```

**Comment by wedesoft** [comment]
Ok, tested it with a Xenial Docker container with X11 and it works on that distribution.

**Comment by wedesoft** [comment]
Any idea how to debug this? I tried `strace` and it seemed to access libraries from `/usr/lib` instead of `/tmp/.mount_anymeaaWxUDE`. I don't understand because `qt.conf` seems to be correct.
