### ISSUE TITLE
Printing selected recipes only prints the last one in list

### ISSUE THREAD

**Issue by Oldbwl** [wedesoft/anymeal#21]
Hi, 
I am selecting several recipes to print, however, only the last one in the list is being printed.

Actually the print preview also only shows one page also.

This is printer independent. I am also having the same issue when using Cups print to PDF.

**Comment by wedesoft** [comment]
Hi,
Ok, I have implemented printing of more than one recipe and release version 1.11.

**Comment by Oldbwl** [comment]
Perfect - I tested and it is fine. - It would be nice if each recipe started on a new page, But I can live with it as is. Thanks

**Comment by wedesoft** [comment]
Ok, thanks for letting me know. Yes, page breaks would be a good idea. I will have a look whether Qt5 has support for it.

**Comment by wedesoft** [comment]
Hi, I found that [Qt5 has support for page breaks](https://doc-snapshots.qt.io/qt5-5.14/richtext-html-subset.html). I have replaced the latest release (version 1.11) with a modified version which inserts page breaks between recipes.

**Comment by Oldbwl** [comment]
You are simply the best. Thank you so much.

There is a tiny ui error, but i can't  get to github to report. If you
position mouse to the right of categories and press delete, you cannot
delete the last comma,. When i have pc again, i will report if req.

**Comment by wedesoft** [comment]
No worries, thanks for trying out the software.
I can't reproduce this error. Is the error in the recipe editor?
Can you tell me step by step how to get there?

**Comment by Oldbwl** [comment]
It is in recipes editor. Am away from pc. From memory, select any recipe
with at least 2 categories, say meat, main, French

Position cursor between the 't' and the comma, backspace to delete the word
meat. Now position cursor to the immediately  to the right of the comma and
backspace to delete. On my set you can't delete the comma, I can get round
it easily, but thought you might like to know.

**Comment by wedesoft** [comment]
Ok, I can reproduce it now as well. This is expected behaviour. I.e. the validator prevents entering a categories string starting with a whitespace character.
