### ISSUE TITLE
Search to exclude categories

### ISSUE THREAD

**Issue by Oldbwl** [wedesoft/anymeal#22]
I am using Anymeal extensively. I find it just perfect and the absence of bloat is very welcome.
I wonder if it is feasible to add a search with/without for the categories as well as ingredients? - or allow REGEX in the search field/box?

I have a specific example. I have 400+ recipes. Sometimes I need to filter to find something which does not have the category "Shelfish" or "Nuts" due someone's intolerance. I know I can achieve this by filtering out all the individual ingredients that are Shellfish or Nuts, but there are so many it takes for ever. However, I do have categories, Shelfish, Meat, Nuts, Cakes etc. Being able to search for entries without those would be so very much quicker.

Stay Safe, 
Dan

**Comment by wedesoft** [comment]
Hi, thanks for the suggestion. I have released [version 1.12](https://github.com/wedesoft/anymeal/releases/tag/v1.12) with the feature to search for recipes with or without a category.

**Comment by wedesoft** [comment]
Stay safe,
Jan

**Comment by Oldbwl** [comment]
Your response on this was most welcome.  Thank you very much indeed.

I will try to leave you alone for a while now, dont want to risk being a
pest. Lol!

**Comment by wedesoft** [comment]
Lol, no worries. Thanks for using the software.
