### ISSUE TITLE
Columns for Ingredients need more padding and headers placed appropriately

### ISSUE THREAD

**Issue by Oldbwl** [wedesoft/anymeal#23]
Hi, I hope you are well during this pandemic.
I show below how the ingredients look like on Anymeal 1.12 

![Screenshot Anymeal](https://user-images.githubusercontent.com/6871305/104021644-08985c80-51b7-11eb-820c-c45da74a4826.jpg)

1. The 1st two columns (see 2 below as well) could do with a bit of padding to separate the unit "tablespoon" etc more as they do look very close to the next column. 

2. Also the Header labels would view better (imho) if they were left aligned - If you agree, that is why the 1st column will need padding so that heading "amount" does not butt up to "unit"

Cheers, Stay safe

**Comment by wedesoft** [comment]
Hi, hope you are ok, too.
I am changing the table headers to be left-aligned. I agree that it reads better.
However changing the cell spacing or padding increases the distance not only horizontally but also vertically. CSS border spacing does not seem to be supported.

**Comment by wedesoft** [comment]
Ok, I realized that I can add an `&nbsp;` (space character) to increase the horizontal cell spacing in the table.

**Comment by wedesoft** [comment]
Ok, it looks like this now:

![sprouts](https://user-images.githubusercontent.com/28663/104385791-c743dc00-552b-11eb-9bd3-db7317d53cad.png)

**Comment by Oldbwl** [comment]
Perfect. Five Star service. I await 1.13 in due course.

**Comment by wedesoft** [comment]
Ok, I have released version 1.13 of the software. Thanks for your suggesting the improvement.
