### ISSUE TITLE
AppImage won't function

### ISSUE THREAD

**Issue by MSOlsen65** [wedesoft/anymeal#24]
I downloaded the AppImage. Made the file executable, however it fails to run at all on my Linux system, openSUSE 15.2

The following messages were returned at the command line:
- /tmp/.mount_anymeaEJpLru/AppRun.wrapped: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_anymeaEJpLru/usr/bin/../lib/libsqlite3.so.0)
- /tmp/.mount_anymeaEJpLru/AppRun.wrapped: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_anymeaEJpLru/usr/bin/../lib/libQt5Core.so.5)
- /tmp/.mount_anymeaEJpLru/AppRun.wrapped: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_anymeaEJpLru/usr/bin/../lib/libsystemd.so.0)
- /tmp/.mount_anymeaEJpLru/AppRun.wrapped: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_anymeaEJpLru/usr/bin/../lib/libsystemd.so.0

Do you have any suggestions to overcome this issue?  I would truly like to give anymeal a fair try.  All reports indicate that it should well fit my needs.

Thanks for any help.

Mike

**Comment by wedesoft** [comment]
Hi, the AppImage requires a recent version of glibc. I wasn't able to get it to work on older systems. However you can build and install it from source. You just need to install the required dependencies.

**Comment by wedesoft** [comment]
I just checked with Google. openSuSE 15.2 still uses glibc version 2.26.

**Comment by MSOlsen65** [comment]
> I just checked with Google. openSuSE 15.2 still uses glibc version 2.26.

Thanks for your help.  I didn't realize that it was so outdated.  I will get things updated and try again.

**Comment by wedesoft** [comment]
Well, 15.2 is the current stable version of openSuSE. So I think your only option is to build from source.

**Comment by MSOlsen65** [comment]
Yes 15.2 is the current stable "business" version (Leap). However, the rolling version (Tumbleweed) is also stable and uses glibc 2.32.  I have long considered "upgrading" to tumbleweed as it better supports several of my science, mathematics, and engineering programs.  Since SUSE is so far behind on this very important library, I believe it may well be time for a change.  Thanks again for being so helpful.  It is truly appreciated.

**Comment by wedesoft** [comment]
Ok, no problem. I didn't know about Tumbleweed. Let me know if you get stuck again.

**Comment by MSOlsen65** [comment]
Hello Jan,

Sorry it has taken so long to get back with you.  Life went a bit nuts for several days, but all is "normal" again.

I have made the switch to Tumbleweed and your AppImage worked flawlessly.  Still checking it out, but so far, it is definitely one of the better one I've tried.  You did a wonderful job.  Thanks again for helping me get started.

Mike

**Comment by wedesoft** [comment]
No worries. Hope everything is ok.
Thanks for reporting back. Glad it works on Tumbleweed. Hope the software is useful to you.
Thanks for closing the issue.
