### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by RAMAR-RAR** [wedesoft/anymeal#25]
I would translate the software. How can do It(Ex. Crowdin, Weblate, etc...)?

**Comment by wedesoft** [comment]
Hi,
The translation files (ts files) can be edited using Qt5 Linguist. Let me know if you want me to send you an empty one.

Kind regards
Jan

On 19 July 2021 21:22:46 BST, RAMAR-RAR ***@***.***> wrote:
>I would translate the software. How can do It(Ex. Crowdin, Weblate,
>etc...)?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wedesoft/anymeal/issues/25

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by wedesoft** [comment]
Ok, I am attaching the zipped ts-file: [anymeal-ts.zip](https://github.com/wedesoft/anymeal/files/6850340/anymeal-ts.zip)

**Comment by wedesoft** [comment]
See [Qt download page](https://www.qt.io/download-qt-installer) for downloading the Qt5 software.

**Comment by RAMAR-RAR** [comment]
How I translate strings with "&" in the middle of a word(Ex. Exp&ort recipes)?

**Comment by wedesoft** [comment]
The "&" is for selecting the alt-hotkey. I.e. "Exp&ort" will choose ALT+O as hotkey. In the translation just select a unique hotkey which makes sense to you.

**Comment by wedesoft** [comment]
See "Exp&ort recipes" for example:

![grafik](https://user-images.githubusercontent.com/28663/127551536-a03379ae-504c-4320-8016-b779ab5559e3.png)

**Comment by RAMAR-RAR** [comment]
[anymeal_ts_it_v2021_07_30.zip](https://github.com/wedesoft/anymeal/files/6908763/anymeal_ts_it_v2021_07_30.zip)

Try this, tell me if there is no problem.

**Comment by wedesoft** [comment]
Looks good! Thanks for providing the translation!

![grafik](https://user-images.githubusercontent.com/28663/127688342-9da826a8-c156-4df8-8716-b55c092cf3b0.png)

**Comment by wedesoft** [comment]
Ok, released version 1.14 with the translation. Thanks.
