### ISSUE TITLE
Compability AnyMeal with EnRecipes

### ISSUE THREAD

**Issue by RAMAR-RAR** [wedesoft/anymeal#27]
Add in future compability between AnyMeal and the android app [EnRecipes](https://github.com/vishnuraghavb/EnRecipes)

**Comment by wedesoft** [comment]
I am hesitant to add export/import for different file formats. It is not possible to do it well because the different formats have different amounts of granularity.

**Comment by wedesoft** [comment]
Also some file formats have pictures and Mealmaster has not.
