### ISSUE TITLE
Blank line instead of line break

### ISSUE THREAD

**Issue by DuebelWalter** [wedesoft/anymeal#28]
Whenever I insert a line break, it turns into a blank line. 
Could you please change this so that I only make a line break with [Enter]? 
Or is there another key combination for this?

**Comment by wedesoft** [comment]
Ok, line breaks create new paragraphs in the output. I'll have a look whether I can convert them to line breaks instead.

**Comment by wedesoft** [comment]
Ok, I fixed it. Thanks for reporting the problem. I released version 1.15.
