### ISSUE TITLE
Is Google test source code really needed? 

### ISSUE THREAD

**Issue by bkmgit** [wedesoft/anymeal#36]
Can a compiled version of Google test be used?

https://github.com/wedesoft/anymeal/blob/master/configure.ac#L22-L28 compiles the source code

**Comment by wedesoft** [comment]
Debian doesn't ship with a compiled version. Sorry for the late response. Must have missed the notification.

**Comment by wedesoft** [comment]
Google tests are now optional. Marking this issue as closed.
