### ISSUE TITLE
Enhancement: Anymeal to remember last selected Encodings

### ISSUE THREAD

**Issue by Oldbwl** [wedesoft/anymeal#37]
I have to select UTF-8 for both imports and exports every-time this function is required. I am importing lots of hand edited single recipes from selected  large lists avail online. In a session I might import 20 or so times, on each import I have to select the Encoding, and it is always the same one. I know I could aggregate and save them for a single bulk import, but my work flow is better suited to importing and assessing the result for errors and mistakes before moving on to the next recipe.

If the program could carry an encoding setting - so that all imports and exports are held to one standard that would be great.

**Comment by wedesoft** [comment]
I did a simpler change, sorry ;)
The import and export dialog in version 1.20 now remember the encoding setting until the program is exited.
Hope that is sufficient.

**Comment by Oldbwl** [comment]
Perfect

**Comment by Oldbwl** [comment]
Thanks - now closed
