### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by bkmgit** [wedesoft/anymeal#39]
- Would it be possible to add the license text at the top of every source file? Can make a pull request with this if ok.
- If so, should all files be GPL-3.0-only or GPL-3.0-or-later?

**Comment by wedesoft** [comment]
I am ok with GPL 3 or later.

**Comment by wedesoft** [comment]
I just checked and the source files seem to have a copyright header. Do you mean the files of the test suite?

**Comment by wedesoft** [comment]
Ok, added license headers to the test suite files.
