### ISSUE TITLE
"New Recipe" option is not avail in any Menu or the Toolbar

### ISSUE THREAD

**Issue by Oldbwl** [wedesoft/anymeal#44]
Like others, I have been importing recipes. But today I have wanted to write one from scratch, copying from hand written notes

To create a new recipe the only way I could find is to right click on an existing recipe (previously imported?), select  "Edit Recipe ", and then select "Edit New" 

"Edit New" is missing from the Edit selection Header bar menu

This sequence will not be obvious to new users. 

May I respectfully suggest that an "Edit (or preferably Create) New" entry to "Edit" header bar selections and a Toolbar button is added.

Additionally, the  shortcut keys to be remapped so that Ctrl+N opens the Edit(Create)New Recipe creation page, and the "Convert Unit" window given another key combination (maybe Ctrl+U).

**Comment by wedesoft** [comment]
Yes, I think that would be better. I guess the menu item could be "File" -> "New"?

**Comment by Oldbwl** [comment]
Sounds right to me.

**Comment by wedesoft** [comment]
Ok, I just released version 1.23 of the software.

**Comment by Oldbwl** [comment]
Awesome
