### ISSUE TITLE
Error Report empty after Import failure when "No MMMMM at end of record"

### ISSUE THREAD

**Issue by Oldbwl** [wedesoft/anymeal#47]
Importing a single file after editing, I received a "0 files imported, 0 files failed" dialogue.

Inspection of /tmp/import-errors.mmf showed the file existed, but was empty.

Manually reviewing the file for import, I noticed the original edited recipe did not have "MMMMM" as the last line.

It took me ages to spot this (bad brain day I think), Adding this missing element allowed the import.

I expected the Error Dialogue to show "0 files imported, 1 file failed" and the import-errors.mmf to say something about end of file missing.

Not urgent or important but I thought I would report here to be useful.

**Comment by wedesoft** [comment]
Ok, thanks for the bug report. I am still thinking about how best to resolve this.

**Comment by wedesoft** [comment]
Ok, I finally added functionality which will report unexpected end of file in the error log file.

**Comment by Oldbwl** [comment]
Perfect. Thanks, now if only you could also take over Garamond, the linux
food space would be doubly blessed,  lol!!!
