### ISSUE TITLE
Version 1.28 - New Category Editor, how to use?

### ISSUE THREAD

**Issue by Oldbwl** [wedesoft/anymeal#50]
The install went perfectly, Version 1.28 is show in the help, but I can find no reference to the new much anticipated Category editor. Nothing new shows in tool bar, nor the drop down menus.

I expect I am just missing it somehow. Can you please advise how this facility is accessed?

many thanks

Dan

**Comment by Oldbwl** [comment]
OK, Scratch this, I found it.

I see that you have to open the category drop down list and select a category and up the editor pops.

Many thanks, 

it looks great

**Comment by wedesoft** [comment]
You need to edit a recipe and then click on the button next to the category label: https://youtu.be/kulLz4Fwg4I
