### ISSUE TITLE
Build Failure for v1.29 - Linux Mint Cinnamon 21.3

### ISSUE THREAD

**Issue by Oldbwl** [wedesoft/anymeal#51]
Extracted the file latest file and followed all the commands in the readme until arrive at  the below  - this has never happened before, all previous versions on this machine have installed on the same commands flawlessly.

~/Downloads/anymeal-1.29$ ./configure --prefix=/usr
bash: ./configure: No such file or directory

The commands was copied and pasted - any idea?

Dan

**Comment by Oldbwl** [comment]
Oops, I found it was my error. took the .gz

**Comment by wedesoft** [comment]
On 29 July 2024 21:35:09 BST, Oldbwl ***@***.***> wrote:
>Oops, I found it was my error. took the .gz  
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/wedesoft/anymeal/issues/51#issuecomment-2256863262
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
Yes, the gz generated by GitHub requires you to run ./autogen.sh first.
