### ISSUE TITLE
CRLF lost when importing from mml file

### ISSUE THREAD

**Issue by pled** [wedesoft/anymeal#52]
Hi,
I am just new to AnyMeal, and try to import my recipes from another software.
I used mml format to import my recipes, and I lost all carriage return from the **instructions** field. I have checked the exported file and CRLF are presents.

Example in mml file : 

```
Faire chauffer l'huile dans la poêle et faire revenir le blanc de l'oignon, la poitrine fumée et les champignons pendant 5 minutes.
Verser la crème et faire chauffer une minute.
Casser les œufs dans la poêle sans crever les jaunes. Laisser cuire 3 à 5 minutes, à feu moyen. Le blanc des œufs doit être cuit.
Saler, poivre, et servir parsemé du vert de l'oignon et de ciboulette ciselée.
```

Result in AnyMeal

`Faire chauffer l'huile dans la poêle et faire revenir le blanc de l'oignon, la poitrine fumée et les champignons pendant 5 minutes. Verser la crème et faire chauffer une minute. Casser les œufs dans la poêle sans crever les jaunes. Laisser cuire 3 à 5 minutes, à feu moyen. Le blanc des œufs doit être cuit. Saler, poivre, et servir parsemé du vert de l'oignon et de ciboulette ciselée. `

File encoding used is ISO-8859-1

**Comment by wedesoft** [comment]
On 1 August 2024 15:22:36 BST, pled ***@***.***> wrote:
>Hi,
>I am just new to AnyMeal, and try to import my recipes from another software.
>I used mml format to import my recipes, and I lost all carriage return from the **instructions** field. I have checked the exported file and CRLF are presents.
>
>Example in mml file : 
>
>```
>Faire chauffer l'huile dans la poêle et faire revenir le blanc de l'oignon, la poitrine fumée et les champignons pendant 5 minutes.
>Verser la crème et faire chauffer une minute.
>Casser les œufs dans la poêle sans crever les jaunes. Laisser cuire 3 à 5 minutes, à feu moyen. Le blanc des œufs doit être cuit.
>Saler, poivre, et servir parsemé du vert de l'oignon et de ciboulette ciselée.
>```
>
>Result in AnyMeal
>
>`Faire chauffer l'huile dans la poêle et faire revenir le blanc de l'oignon, la poitrine fumée et les champignons pendant 5 minutes. Verser la crème et faire chauffer une minute. Casser les œufs dans la poêle sans crever les jaunes. Laisser cuire 3 à 5 minutes, à feu moyen. Le blanc des œufs doit être cuit. Saler, poivre, et servir parsemé du vert de l'oignon et de ciboulette ciselée. `
>
>File encoding used is ISO-8859-1
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/wedesoft/anymeal/issues/52
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
Mealmaster uses double returns for paragraphs. Alternatively you can add a colon at the beginning of the line.
Kind regards
Jan

**Comment by pled** [comment]
Thank you for your quick answer. 
I saw [your page](https://www.wedesoft.de/software/2020/07/07/mealmaster/) to correct my exported file which have some other errors. But with the help of regular expressions, I should be able to get it as it should. :+1:

**Comment by wedesoft** [comment]
Ok. Let me know if there are any more problems.
