### ISSUE TITLE
Cannot Edit imported recipe

### ISSUE THREAD

**Issue by pled** [wedesoft/anymeal#53]
Hi, still new to AnyMeal ! ;-)

I cannot Edit imported recipe. As soon as modifying ingredients or instructions, OK button is greyed out.

I can edit a new recipe created with AnyMeal though.

**Comment by wedesoft** [comment]
On 2 August 2024 10:31:15 BST, pled ***@***.***> wrote:
>Hi, still new to AnyMeal ! ;-)
>
>I cannot Edit imported recipe. As soon as modifying ingredients or instructions, OK button is greyed out.
>
>I can edit a new recipe created with AnyMeal though.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/wedesoft/anymeal/issues/53
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
Make sure categories and servings are not empty in the first editor tab.

**Comment by pled** [comment]
They are not empty.

I right click on the recipe, and choose "Modify recipe", then select "modify current recipe".
When the edit windows opens, I can only modify "Quantity" on the first tab and save. 
Everything else : "Title" on first tab, or any other field on other tabs, OK button is immediately greyed out, and never comes back.

![Capture d’écran du 2024-08-02 14-36-03](https://github.com/user-attachments/assets/edf5ad3e-2d83-408c-b44b-0d3b137165fd)

![Capture d’écran du 2024-08-02 14-46-53](https://github.com/user-attachments/assets/72283208-044b-429f-a4ca-01045c3411e1)

**Comment by wedesoft** [comment]
On 2 August 2024 13:49:22 BST, pled ***@***.***> wrote:
>They are not empty.
>
>I right click on the recipe, and choose "Modify recipe", then select "modify current recipe".
>When the edit windows opens, I can only modify "Quantity" on the first tab and save. 
>Everything else : "Title" on first tab, or any other field on other tabs, OK button is immediately greyed out, and never comes back.
>
>![Capture d’écran du 2024-08-02 14-36-03](https://github.com/user-attachments/assets/edf5ad3e-2d83-408c-b44b-0d3b137165fd)
>
>![Capture d’écran du 2024-08-02 14-46-53](https://github.com/user-attachments/assets/72283208-044b-429f-a4ca-01045c3411e1)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/wedesoft/anymeal/issues/53#issuecomment-2265320212
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
Can you send me the Mealmaster file?

**Comment by pled** [comment]
You will find a sample recipe here : 
https://pled.fr/transfer/Test.mmf

Once imported, I cannot modify it. Tested on both Debian 13 and Debian 12.

I also notice another "problem" : when using Gourmand (aka Gourmet) to export my recipes to mml format, I can see some ingredients quantity like this : 
`150-200 g  de légumes par personne`
which is no accepted on import. (It is useful when you want to give a range in quantity).
When I use My CookBook app (android) to export to mml, it comes to : 
`    150    -200 g de légumes par personne`
which is accepted.
Is it expected ? From [your document](https://www.wedesoft.de/software/2020/07/07/mealmaster/), 1 to 7 characters are used for quantity, but there is no exception mentionned. Are only numbers supported ?

Thank you for your help.

**Comment by wedesoft** [comment]
Hi, the recipe is missing the yield type. It is "4" but you need to enter the type as well in the edit dialog (e.g. "portions"). Maybe I need to add a message to the dialog to explain why the ok button is disabled.
Regarding ranges, Mealmaster does not accept ranges. It only supports numbers like "150", "1/2", "2 1/4", "1.5".

**Comment by pled** [comment]
Thank you, it works now.
A small remark : in the main window, "instructions" should be "Instructions" (at least for french language) : 
![Capture d’écran du 2024-08-04 11-38-02](https://github.com/user-attachments/assets/860f4569-faf5-4d74-806b-a0612d8bc7b0)

Again, thank you for your help and the quick answers ! :+1:

**Comment by wedesoft** [comment]
Ok, I added a message to the dialog explaining why the ok-button is disabled (released in version 1.30).

![anymeal-error](https://github.com/user-attachments/assets/d5129b33-390f-4727-bdcf-d9ab83b8b5ad)
