### ISSUE TITLE
Add option to choose app language

### ISSUE THREAD

**Issue by anzepintar** [wedesoft/anymeal#55]
Please add an option to choose the language in which is app displayed, I believe it currently works by locale preferences on linux and possibly something similar on windows.
Related: Pull request: #56 - Slovenian translation

**Comment by wedesoft** [comment]
Ok, added a menu for switching language in version 1.30.

![anymeal-language](https://github.com/user-attachments/assets/330ec787-71a9-4434-a136-31c13e249e75)
