### ISSUE TITLE
Undefined behavior when having longer recipe titles

### ISSUE THREAD

**Issue by anzepintar** [wedesoft/anymeal#60]
Undefined behavior when having character ž in recipe title:
How to reproduce:
1. option: Set aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa as title of the recipe and then click on button Show all recipes. 
2. option: Create new recipe with name containing 8 "ž" characters and then click on button Show all recipes
8*ž = recipes.servings
9*ž = recipes.servingsun
.
.
.
16*ž = ����2e

**Comment by wedesoft** [comment]
Thanks for reporting this bug. Looks like I was using the return value of recipe.title().c_str() beyond it's lifetime!

**Comment by wedesoft** [comment]
Ok, fixed in version 1.31.
