### ISSUE TITLE
Debian : no icon displayed in the Gnome dash

### ISSUE THREAD

**Issue by pled** [wedesoft/anymeal#62]
Hi, 

After installing Anymeal 1.18-2 from debian 12 repository, there is no icon displayed in the dash when anymeal is running, while icon is displayed in the Gnome search : 

![anymeal-icon](https://github.com/user-attachments/assets/f3ad7bc5-32c7-4437-aca6-9f0064ed4a93)

Gnome-shell is v43.9, no extension activated.

To get the icon, I need to create a application file like `~/.local/share/applications/anymeal.desktop` : 

```
[Desktop Entry]
Name=Anymeal
Comment=Anymeal Recipe Manager
Exec=/usr/bin/anymeal
Icon=/usr/share/icons/hicolor/256x256/apps/anymeal.png
Terminal=False
Type=Application
Categories=Misc;
```
(there might other ways to achieve that, I don't know)

Result : 
![Capture d’écran du 2024-08-06 11-12-44](https://github.com/user-attachments/assets/0844d8ca-05f8-4737-95bf-aa664829d41e)

But doing this, I know have two icons in Gnome search : 

![Capture d’écran du 2024-08-06 11-16-33](https://github.com/user-attachments/assets/aff3e6bf-c87b-4cb6-a7c6-3a58cab1c969)

Note for that example, I created a new icon for the fun : 

![recipes-icon-anymeal](https://github.com/user-attachments/assets/8523dda5-0d13-40f3-bf91-c8d8e8abdd10)

Because apart of the issue, and this is just a suggestion, and something that comes to my mind when launching Anymeal at first time, Anymeal icon is not very graphical in my opinion (just a casserole picture). May be your opinion is different, so you may ignore this.

Icon is taken from that page which list some free icons related to recipes software : 
https://www.freeiconspng.com/images/recipes-icon-png

It is easy to start from one of these ones (or any other free icon one can find ), and modify it to match Anymeal software.

**Comment by wedesoft** [comment]
On 6 August 2024 10:24:11 BST, pled ***@***.***> wrote:
>Hi, 
>
>After installing Anymeal 1.18-2 from debian 12 repository, there is no icon displayed in the dash when anymeal is running, while icon is displayed in the Gnome search : 
>
>![anymeal-icon](https://github.com/user-attachments/assets/f3ad7bc5-32c7-4437-aca6-9f0064ed4a93)
>
>Gnome-shell is v43.9, no extension activated.
>
>To get the icon, I need to create a application file like `~/.local/share/applications/anymeal.desktop` : 
>
>```
>[Desktop Entry]
>Name=Anymeal
>Comment=Anymeal Recipe Manager
>Exec=/usr/bin/anymeal
>Icon=/usr/share/icons/hicolor/256x256/apps/anymeal.png
>Terminal=False
>Type=Application
>Categories=Misc;
>```
>(there might other ways to achieve that, I don't know)
>
>Result : 
>![Capture d’écran du 2024-08-06 11-12-44](https://github.com/user-attachments/assets/0844d8ca-05f8-4737-95bf-aa664829d41e)
>
>But doing this, I know have two icons in Gnome search : 
>
>![Capture d’écran du 2024-08-06 11-16-33](https://github.com/user-attachments/assets/aff3e6bf-c87b-4cb6-a7c6-3a58cab1c969)
>
>Note for that example, I created a new icon for the fun : 
>
>![recipes-icon-anymeal](https://github.com/user-attachments/assets/8523dda5-0d13-40f3-bf91-c8d8e8abdd10)
>
>Because apart of the issue, and this is just a suggestion, and something that comes to my mind when launching Anymeal at first time, Anymeal icon is not very graphical in my opinion (just a casserole picture). May be your opinion is different, so you may ignore this.
>
>Icon is taken from that page which list some free icons related to recipes software : 
>https://www.freeiconspng.com/images/recipes-icon-png
>
>It is easy to start from one of these ones (or any other free icon one can find ), and modify it to match Anymeal software.
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/wedesoft/anymeal/issues/62
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
Did you try to restart GNOME after installation of Anymeal? Anymeal installs a desktop file and icon in the correct locations when configuring with prefix "/usr".
Kind regards
Jan

**Comment by pled** [comment]
Yes, machine has been restarted. Anymeal is installed using `sudo apt install anymeal`.  I can see your files : 
```
/usr/share/icons/hicolor/64x64/apps/anymeal.png
/usr/share/applications/de.wedesoft.anymeal.desktop
```
Doing some more tests, it seems to work when renaming the file from `de.wedesoft.anymeal.desktop` to `anymeal.desktop`, although icon is long to display in Dash (like 10secs). 

But all this is beyond my knowledge...

I have this behavior with both Debian 12 (VM) and Debian 13 trixie (desktop).

**Comment by wedesoft** [comment]
Sorry, I can't reproduce it on Debian 12. I installed GNOME and then did `sudo apt install anymeal` which install Anymeal 1.18. Running the software shows the icon in both the search and the dash.

![image](https://github.com/user-attachments/assets/91332d15-75c5-4dd1-9903-e0f712cecd06)

**Comment by pled** [comment]
Hum... very strange : I created a new fresh VM with Debian 12.6 ISO, then install anymeal : issue is there.

![Capture d’écran du 2024-08-07 11-08-06](https://github.com/user-attachments/assets/32f0d969-5d9f-41f5-a577-cb6f58f4b6aa)

and same behaviour : renaming de.wedesoft.anymeal.desktop to anymeal.desktop make sicon appears in the dash, but after around 10 seconds...

![Capture d’écran du 2024-08-07 11-11-12](https://github.com/user-attachments/assets/0f67b522-375e-4735-b9a6-23a0788c2c48)

**Comment by wedesoft** [comment]
Does it work if you instead move /usr/share/icons/hicolor/64x64/apps/anymeal.png to  /usr/share/icons/hicolor/64x64/apps/de.wedesoft.anymeal.png and update the Icon entry in the desktop file accordingly?

**Comment by wedesoft** [comment]
I.e. keep the desktop file at /usr/share/applications/de.wedesoft.anymeal.desktop but change the PNG file name instead.

**Comment by pled** [comment]
It does not work. I renamed icon file to de.wedesoft.anymeal.png, then tried changing icon definition in the  /usr/share/applications/de.wedesoft.anymeal.desktop. Tried both : 
`Icon=de.wedesoft.anymeal`
and
`Icon=de.wedesoft.anymeal.png`

Same result : icon is no more displayed at all.

![Capture d’écran du 2024-08-08 09-36-15](https://github.com/user-attachments/assets/27dfa5eb-3980-40f6-8130-4a2727364470)

**Comment by wedesoft** [comment]
Ok, when I install Debian in VirtualBox, I can see the same problem. Not sure how to solve it yet.

**Comment by wedesoft** [comment]
I also set StartupNotify=false in the desktop file to get rid of the annoying busy indicator.

**Comment by wedesoft** [comment]
Looks like the busy indicator is still there, don't know why.

**Comment by wedesoft** [comment]
Ah, had to restart GNOME for it to work.

**Comment by pled** [comment]
Yes, it works with these settings.
I still notice around 10 seconds (or more) to have the icon appear in the dash bar. 
If I launch anymeal from a terminal window, the icon is immediately displayed.
Do you experience the same in the VirtualBox VM ?

**Comment by pled** [comment]
Perfect, icon is there and on time with these settings. Thank you.
