### ISSUE TITLE
Upgrade to Qt6

### ISSUE THREAD

**Issue by bkmgit** [wedesoft/anymeal#66]
Happy to work on this.

**Comment by wedesoft** [comment]
Ok, you can clone Anymeal and port it over. I can review your changes and test it. Probably the AppImage and the NSIS installer script for Windows will need changing as well.

**Comment by bkmgit** [comment]
https://github.com/wedesoft/anymeal/commit/ecbdba59ad77cbe213723c92686dac738c324d0f
