### ISSUE TITLE
recipe editing

### ISSUE THREAD

**Issue by wedesoft** [wedesoft/anymeal#8]
It should be possible to edit existing and new recipes.

**Comment by meonkeys** [comment]
Is there a way to create a new recipe in the app?

**Comment by wedesoft** [comment]
On 20 April 2023 14:48:30 BST, Adam Monsen ***@***.***> wrote:
>Is there a way to create a new recipe in the app?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/wedesoft/anymeal/issues/8#issuecomment-1516364585
>You are receiving this because you modified the open/close state.
>
>Message ID: ***@***.***>
Yes, go to "Edit" and then click the "Edit Recipe" menu entry. If you have selected a recipe already, you need to click "Edit New" in the following dialog.
Kind regards
Jan

--
Sent using K-9 Mail on Xiaomi Redmi 5A.
https://www.wedesoft.de/
